### ISSUE TITLE
关于预训练的问题

### ISSUE THREAD

**Issue by Windysum** [wangwang110/ChineseBert_CSC#1]
请问用wang2018数据集先预训练是啥意思呀，看了一下它里面有训练集和校验集，是用wang的训练集先当做模型的训练集，从中训练出loss最小的模型再用sighan13的测试集来计算指标吗？还是？新手，请老师指点一下

**Comment by wangwang110** [comment]
我的意思是先用wang2018训练，再用sighan数据训练。这样做比之间将wang2018和sighan混在一起训练好
